name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.12
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  provider: ^6.1.2
  go_router: ^14.2.0
  path_provider: ^2.1.3
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_dotenv: ^5.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  generate: true
  uses-material-design: true
  assets:
    [".env"]
